# Generated by Django 3.1.4 on 2021-02-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_auto_20200906_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='dob',
        ),
    ]
